### ISSUE TITLE
Does anyone manage the GetSatisfaction site?

### ISSUE THREAD

**Issue by vossad01** [scala/scala.github.com#645]
https://getsatisfaction.com/scaladocs is still linked in the footer as "Suggestions".  It has recent traffic, but it does not seem that anyone has responded to users there in about 3 years.

Perhaps that should be shut down and users linked to this issue tracker instead.

**Comment by heathermiller** [comment]
We did use it, but there was about 1-2 years in the middle there where no user provided any feedback. Since I was the only person maintaining the website then, and since for a long stint no user was providing feedback via GetSatisfaction, it fell out of my routine to check it and respond to it (plus I think my gmail account started filtering GetSatisfaction emails out as spam). Also, until very recently GetSatisfaction seemed like it might be dying... 

Removing it from the site + linking to the issue tracker is indeed a better idea.

**Comment by SethTisue** [comment]
oh no, I had no idea this even existed

**Comment by heathermiller** [comment]
o_o sorry

**Comment by SethTisue** [comment]
no worries, if I didn't know about it, that means almost nobody did, which means it's not that big a deal!

**Comment by Philippus** [comment]
the link now goes to http://retired.getsatisfaction.com/
If this is intentional the link should be removed.

**Comment by SethTisue** [comment]
https://github.com/scala/scala.github.com/pull/778
